kind: pipeline
name: default

steps:
- name: test
  image: .
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t newisn .
  - docker login -u reoltech -p Reolus@123
  - docker push newisn
  - echo "Hello"
