pipeline:
 mytask:
   image: https://github.com/PratikSaheb/lastone/blob/master/Dockerfile
   script:
    - docker build -t newis https://github.com/PratikSaheb/lastone/blob/master/Dockerfile
    - echo docker ps -a
   when:
    event: push
