pipeline:
 mytask:
  image: node:alpine 
  script:
   - docker build -t newist .
   - docker ps -a
   - docker login -u reoltech -p Reolus@123
   - docker image tag newist reoltech/ns:1
   - docker image push reoltech/ns:1
   - echo "done"
  when:
    event: push
