kind: pipeline
name: default

steps:
- name: test
  image: /ko/Dockerfile
  volumes:
  - name: dockersock
    path: /ko/
  commands:
  - docker build -t newisn .
  - docker login -u reoltech -p Reolus@123
  - docker push newisn
  - echo "Hello"
